<?xml version="1.0"?>
<package format="3">
  <name>home_robotics_description</name>
  <version>0.1.0</version>
  <description>Dual rail-mounted Franka Panda robot description for Home Robotics.</description>
  <maintainer email="esat.kolay19@gmail.com">mek</maintainer>
  <license>NOASSERTION</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>home_robotics_mujoco_hardware</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
